services:
  - type: web
    name: test_flask_api
    env: python
    pythonVersion: 3.12
    buildCommand: python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
